[package]
name = "example_submission_2"
version = "0.1.0"
edition = "2021"

[dependencies]
rplcs_events = { path = "rplcs_events" }
# rplcs_events = { path = "../../../rplcs_events" }
axum = "0.8"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
